name: Build CFST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # Ganti dengan versi Go yang diinginkan

    - name: Build cfst.go for amd64
      run: |
        GOARCH=amd64 GOOS=linux go build -o linux-amd64 cfst.go

    - name: Build cfst.go for 386
      run: |
        GOARCH=386 GOOS=linux go build -o linux-386 cfst.go

    - name: Build cfst.go for arm64
      run: |
        GOARCH=arm64 GOOS=linux go build -o linux-arm64 cfst.go

    - name: Build cfst.go for arm
      run: |
        GOARCH=arm GOOS=linux GOARM=7 go build -o linux-arm cfst.go

    - name: Build termux.go for amd64
      run: |
        GOARCH=amd64 GOOS=linux go build -o termux-amd64 termux.go

    - name: Build termux.go for 386
      run: |
        GOARCH=386 GOOS=linux go build -o termux-386 termux.go

    - name: Build termux.go for arm64
      run: |
        GOARCH=arm64 GOOS=linux go build -o termux-arm64 termux.go

    - name: Build termux.go for arm
      run: |
        GOARCH=arm GOOS=linux GOARM=7 go build -o termux-arm termux.go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: go-builds
        path: |
          linux-amd64
          linux-386
          linux-arm64
          linux-arm
          termux-amd64
          termux-386
          termux-arm64
          termux-arm

    - name: Upload build results to GitHub repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p tools/linux/cfst
        mkdir -p tools/termux/cfst
        cp linux-* tools/linux/cfst/
        cp termux-* tools/termux/cfst/
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add tools/linux/cfst
        git add tools/termux/cfst
        git commit -m "Add build artifacts"
        git push
